//8. clone app
const MyMenuData = [
  {
    id: 1,
    image: "Images/Api-image-data/maggi.jpg",
    name: "maggi",
    category: "breakfast",
    price: "₹30",
  },

  {
    id: 2,
    image: "Images/Api-image-data/allupakoida.jpg",
    name: "allu pakodia",
    category: "evening",
    price: "₹25",
  },
  {
    id: 3,
    image: "Images/Api-image-data/corn.jpg",
    name: "corn",
    category: "breakfast",
    price: "₹15",
  },
  {
    id: 4,
    image: "Images/Api-image-data/chola.jpg",
    name: "chola",
    category: "lunch",
    price: "₹50",
  },
  {
    id: 5,
    image: "Images/Api-image-data/pizza.jpg",
    name: "pizza",
    category: "evening",
    price: "₹80",
  },
  {
    id: 6,
    image: "Images/Api-image-data/nonvegthali.jpg",
    name: "Non-Veg Thali",
    category: "dinner",
    price: "₹180",
  },
  {
    id: 7,
    image: "Images/Api-image-data/sweet.jpg",
    name: "Sweets",
    category: "dinner",
    price: "₹60",
  },
  {
    id: 8,
    image: "Images/Api-image-data/rajmarice.jpg",
    name: "Rajma Rice",
    category: "lunch",
    price: "₹60",
  },
  {
    id: 9,
    image: "Images/Api-image-data/samosa.jpg",
    name: "samosa",
    category: "evening",
    price: "₹10",
  },
  {
    id: 10,
    image: "Images/Api-image-data/sirloin.jpg",
    name: "Grilled sirloin",
    category: "breakfast",
    price: "₹150",
  },
  {
    id: 11,
    image: "Images/Api-image-data/tso-chicken.jpg",
    name: "Tso's Chicken",
    category: "dinner",
    price: "₹180",
  },
  {
    id: 12,
    image: "Images/Api-image-data/grilled-steak-salad.jpg",
    name: "Grilled Steak",
    category: "breakfast",
    price: "₹150",
  },
  {
    id: 13,
    image: "Images/Api-image-data/french-fries&steak.jpg",
    name: "Fries & Steak",
    category: "lunch",
    price: "₹150",
  },
  {
    id: 14,
    image: "Images/Api-image-data/barbecue-grill.png",
    name: "Barbecue Grill",
    category: "dinner",
    price: "₹250",
  },
  {
    id: 15,
    image: "Images/Api-image-data/momo.jpg",
    name: "Momos",
    category: "evening",
    price: "₹50",
  },
  {
    id: 16,
    image: "Images/Api-image-data/pau-bhaji.jpg",
    name: "Phav Bhaji",
    category: "breakfast",
    price: "₹20",
  },
  {
    id: 17,
    image: "Images/Api-image-data/puri.jpg",
    name: "Puri",
    category: "lunch",
    price: "₹10",
  },
  {
    id: 18,
    image: "Images/Api-image-data/chicken-plate-roti.jpg",
    name: "Chicken & Roti",
    category: "lunch",
    price: "₹180",
  },
  {
    id: 19,
    image: "Images/Api-image-data/vegthali.jpg",
    name: "Veg Thali",
    category: "dinner",
    price: "₹150",
  },
]
export default MyMenuData;